version: "3.9"
services:
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8095:80"
  api:
    build: royal
  frontend:
    build: rumble
    ports:
      - "5173:5173"
