events {}
http {
    server {
        listen 80;
        listen 443 default_server ssl;
        server_name _;
        ssl_certificate /etc/nginx/certs/suffroyale.com.cer;
        ssl_certificate_key /etc/nginx/certs/suffroyale.com.key;

        location /api/ {
            proxy_pass http://api;
        }

        location / {
            proxy_pass http://frontend:5173;
        }
    }
}
